project_id = "unsznbmmqhihwctguvvr"

[functions.coletar-metricas-meta]
verify_jwt = false

[functions.coletar-metricas-google]
verify_jwt = false

[functions.calcular-metricas-semanais]
verify_jwt = false

[functions.sincronizar-pipedrive]
verify_jwt = false

[functions.sincronizar-tokeniza]
verify_jwt = false

[functions.coletar-criativos-meta]
verify_jwt = false

[functions.coletar-criativos-google]
verify_jwt = false

[functions.pipedrive-webhook]
verify_jwt = false

[functions.gerar-sugestoes-acoes]
verify_jwt = true

[functions.analise-inteligencia]
verify_jwt = false

[functions.enriquecer-lead-mautic]
verify_jwt = false

[functions.importar-campanhas-meta]
verify_jwt = false

[functions.importar-campanhas-google]
verify_jwt = false

