project_id = "unsznbmmqhihwctguvvr"

[functions.coletar-metricas-meta]
verify_jwt = false

[functions.coletar-metricas-google]
verify_jwt = false

[functions.calcular-metricas-semanais]
verify_jwt = false

[functions.sincronizar-pipedrive]
verify_jwt = false

[functions.sincronizar-tokeniza]
verify_jwt = false